name: Build Kivy APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk python3-venv cmake autoconf automake libtool m4

      - name: Build APK
        run: |
          pip3 install --user --upgrade buildozer
          export PATH=$PATH:~/.local/bin
          # Gunakan --no-deps agar tidak memicu autoreconf pada library C
          buildozer android debug
        env:
          # Memaksa agar tidak melakukan auto-reconf yang rusak
          NO_AUTORECONF: "1"

      - uses: actions/upload-artifact@v4
        with:
          name: MagicalForest-APK
          path: bin/*.apk
